language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
addons:
  apt:
    packages:
      - libaio-dev
      - libnuma-dev
      - libjemalloc-dev
      - libmysqlclient-dev
      - libmysqld-dev
      - libwrap0-dev
      - libstdc++5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmysqlclient-dev libmysqld-dev libwrap0-dev libaio-dev
  - perlbrew install-cpanm -f
  - mysql -e 'CREATE DATABASE IF NOT EXISTS myapp_test;'
  - mysql -e "grant all privileges on myapp_test.* to 'travis'@'localhost' identified by 's3kr1t';"
env:
  global:
    - "HARNESS_OPTIONS=j1 TEST_ONLINE_mysql=mysql://travis:s3kr1t@localhost/myapp_test"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n Scalar::Util String::Random Mojo::mysql Mojo::SQLite CellBIS::Random CellBIS::SQL::Abstract"
script: prove -lvr t
sudo: false
notifications:
  email: false
